-- Создать таблицу ролей
CREATE TABLE IF NOT EXISTS public.roles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_daily_participant boolean DEFAULT true,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_key UNIQUE (name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.roles
    OWNER to gen_user;

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.roles TO gen_user;

-- Вставка (заполнение) ролей
INSERT INTO roles (name) VALUES ('Developer') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name) VALUES ('QA') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name) VALUES ('Team Lead') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name) VALUES ('PM') ON CONFLICT (name) DO NOTHING;

-- Создать таблицу пользователей
CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    chat_id bigint NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    role_id integer NOT NULL,
    is_daily_participant boolean NOT NULL,
    created_at timestamp without time zone NOT NULL,
    timezone character varying(50) COLLATE pg_catalog."default" DEFAULT 'Europe/Moscow'::character varying,
    email character varying(255) COLLATE pg_catalog."default",
    tracker_user_id character varying(255) COLLATE pg_catalog."default",
    current_task_key character varying(50) COLLATE pg_catalog."default",
    daily_active boolean DEFAULT false,
    telegram_username character varying(100) COLLATE pg_catalog."default",
    task_assigned_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_chat_id_key UNIQUE (chat_id),
    CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT users_email_format CHECK (email::text ~ '^[^@]+@[^@]+\.[^@]+$'::text)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to gen_user;

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.users TO gen_user;
-- Index: idx_users_chat_id

-- DROP INDEX IF EXISTS public.idx_users_chat_id;

CREATE INDEX IF NOT EXISTS idx_users_chat_id
    ON public.users USING btree
    (chat_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: idx_users_email

-- DROP INDEX IF EXISTS public.idx_users_email;

CREATE INDEX IF NOT EXISTS idx_users_email
    ON public.users USING btree
    (email COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Создать таблицу проверок Checkins
CREATE TABLE IF NOT EXISTS public.checkins
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    checkin_date date NOT NULL,
    answer_yesterday text COLLATE pg_catalog."default" NOT NULL,
    answer_today text COLLATE pg_catalog."default" NOT NULL,
    answer_blockers text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL,
    task_id character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT checkins_pkey PRIMARY KEY (id),
    CONSTRAINT checkins_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.checkins
    OWNER to gen_user;

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.checkins TO gen_user;
-- Index: idx_checkins_date

-- DROP INDEX IF EXISTS public.idx_checkins_date;

CREATE INDEX IF NOT EXISTS idx_checkins_date
    ON public.checkins USING btree
    (checkin_date ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: idx_checkins_user_date

-- DROP INDEX IF EXISTS public.idx_checkins_user_date;

CREATE INDEX IF NOT EXISTS idx_checkins_user_date
    ON public.checkins USING btree
    (user_id ASC NULLS LAST, checkin_date ASC NULLS LAST)
    TABLESPACE pg_default;

-- Создать таблицу журналов Logs
CREATE TABLE IF NOT EXISTS public.logs
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    date date NOT NULL,
    question_number integer NOT NULL,
    raw_answer text COLLATE pg_catalog."default" NOT NULL,
    answer_length integer NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    CONSTRAINT logs_pkey PRIMARY KEY (id),
    CONSTRAINT logs_role_id_fkey FOREIGN KEY (role_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT logs_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.logs
    OWNER to gen_user;

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.logs TO gen_user;
-- Index: idx_logs_user_date

-- DROP INDEX IF EXISTS public.idx_logs_user_date;

CREATE INDEX IF NOT EXISTS idx_logs_user_date
    ON public.logs USING btree
    (user_id ASC NULLS LAST, date ASC NULLS LAST)
    TABLESPACE pg_default;